In [70]:
#create the list of schools we want to study
schools = {
    'ironhack': 10828,
    'app-academy': 10525,
    'le-wagon': 10868,
    'ubiqum-code-academy': 11111,
    'udacity': 11118,
}

import re
import pandas as pd
from pandas.io.json import json_normalize
import requests



def get_comments_school(school):
    #create a regex expressionn that will search for the html tags
    TAG_RE = re.compile(r'<[^>]+>')
    # defines url to make api call to data -> dynamic with school if you want to scrape competition
    url = "https://www.switchup.org/chimera/v1/school-review-list?mainTemplate=school-review-list&path=%2Fbootcamps%2F" + school + "&isDataTarget=false&page=3&perPage=10000&simpleHtml=true&truncationLength=250"
    # makes get request and converts answer to json
    # url defines the page of all the information, request is made, and information is returned to data variable
    data = requests.get(url).json()
    # converts json to dataframe
    reviews = pd.DataFrame(data['content']['reviews'])

    # aux function to apply regex and remove tags
    def remove_tags(x):
        return TAG_RE.sub('', x)
    #create a column in reviews "review_body" that will be populated with another columns created 'body' that will be remove all the html tags
    reviews['review_body'] = reviews['body'].apply(remove_tags)
    # create a column 'school' with the school
    reviews['school'] = school
    #return the table with all the reviews of a defined school
    return reviews




#list comprehension
comments=[get_comments_school(school) for school in schools.keys()]

comments = pd.concat(comments)

from pandas.io.json import json_normalize


def get_school_info(school, school_id):
    #create the URL for each school
    url = 'https://www.switchup.org/chimera/v1/bootcamp-data?mainTemplate=bootcamp-data%2Fdescription&path=%2Fbootcamps%2F' + str(
        school) + '&isDataTarget=false&bootcampId=' + str(
        school_id) + '&logoTag=logo&truncationLength=250&readMoreOmission=...&readMoreText=Read%20More&readLessText=Read%20Less'

    #create a json fil
    data = requests.get(url).json()

    data.keys()

    courses = data['content']['courses']
    courses_df = pd.DataFrame(courses, columns=['courses'])

    locations = data['content']['locations']
    locations_df = json_normalize(locations)

    badges_df = pd.DataFrame(data['content']['meritBadges'])

    website = data['content']['webaddr']
    description = data['content']['description']
    logoUrl = data['content']['logoUrl']
    school_df = pd.DataFrame([website, description, logoUrl]).T
    school_df.columns = ['website', 'description', 'LogoUrl']

    locations_df['school'] = school
    courses_df['school'] = school
    badges_df['school'] = school
    school_df['school'] = school

    # how could you write a similar block of code to the above in order to record the school ID?

    locations_df['school_id'] = school_id
    courses_df['school_id'] = school_id
    badges_df['school_id'] = school_id
    school_df['school_id'] = school_id

    return locations_df, courses_df, badges_df, school_df


locations_list = []
courses_list = []
badges_list = []
schools_list = []

for school, id in schools.items():
    a, b, c, d = get_school_info(school, id)

    locations_list.append(a)
    courses_list.append(b)
    badges_list.append(c)
    schools_list.append(d)

locations = pd.concat(locations_list)
courses = pd.concat(courses_list)
badges = pd.concat(badges_list)
schools = pd.concat(schools_list)
schools = pd.concat(schools_list)


#functions for data cleaning
def remove_tags_url(x):
    TAG_RE = re.compile("/.*$")
    return TAG_RE.sub('', x)

def remove_tags_html(x):
    TAG_RE = re.compile(r'<[^>]+>')
    return TAG_RE.sub('', x)

def convert_integer(x):
    if type(x)==float:
        x=int(x)
    else:
        x
    return x

#schools data cleaning
schools['description'] = schools['description'].apply(remove_tags_html)
schools['website'] = schools['website'].apply(remove_tags_url)
#schools droping tables
schools=schools.drop(['LogoUrl'], axis=1)

#badges data cleaning
badges['description'] = badges['description'].apply(remove_tags_html)


#comments data cleaning
comments['body'] = comments['body'].apply(remove_tags_html)
comments['graduatingYear'].fillna(0, inplace=True)
comments['graduatingYear']
comments['graduatingYear']=comments['graduatingYear'].apply(convert_integer)

#comments droping tables
comments=comments.drop(['queryDate'], axis=1)
comments=comments.drop(['user'], axis=1)
comments=comments.drop(['comments'], axis=1)




#Joan course data cleaning
mydict = {}

for x in courses['courses'].unique():
    if x not in mydict.keys():
        mydict[x] = 0
    else:
        continue



def word_finder(keys):
    global mydict

    a = set(['data', 'analytics', 'analyst', 'science', 'python', 'react', 'artificial', 'AI', 'deep', 'machine','learning', 'natural'])
    b = set(['web', 'development', 'android', 'ios', 'java','fullstack'])
    c = set(['UX', 'UI', 'design', 'designer'])
    d = set(['software', 'engineer'])

    for key in keys:
        if len(a.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'data analysis/data science' + ' related course'
            # break
        elif len(b.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'web development' + ' related course'
            # break
        elif len(c.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'UX/UI Design' + ' related course'
            # break
        elif len(d.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'Back end development' + ' related course'
            # break
        elif key == "No informations":
            mydict[key] = "No Informations"
        else:
            mydict[key] = 'other courses'

    return mydict


word_finder(list(mydict.keys()))

a = courses['courses']
courses['courses by group'] = a #create a new column
courses['courses by group'] = courses['courses by group'].replace(mydict)

#identification of online/offline courses
mydict1 = {}
for x in comments['school'].unique():
    if x not in mydict1.keys():
        mydict1[x] = 0
    else:
        continue
mydict1
print(list(mydict1.keys()))
def online_offline(keys):
    global mydict1
    for key in keys:
        if key.lower() == 'ironhack' or key.lower() == 'app-academy':
            mydict1[key] = 'Online/Offline'
        elif key.lower() == 'le-wagon' or key.lower() == 'ubiqum-code-academy':
            mydict1[key] = 'Online'
        elif key.lower() == 'udacity':
            mydict1[key] = 'Offline'
    return mydict1
online_offline(list(mydict1.keys()))
online_offline_column = comments['school']
comments['Online/Offline'] = online_offline_column
comments['Online/Offline'] = comments['Online/Offline'].replace(mydict1)

list_to_drop=['country.id','country.abbrev','city.keyword','state.id','state.name','state.abbrev','state.keyword','city.id','description']
for x in list_to_drop:
    locations=locations.drop([x], axis=1)
    
courses["index"]=courses.index
courses['courses_id']=courses['school_id'].apply(str) + "_"+ courses["index"].apply(str)
courses['concat']=courses['school_id'].apply(str)+courses['courses by group']

comments['program'].fillna("No informations", inplace=True)

mydict = {}

for x in comments['program'].unique():
    if x not in mydict.keys():
        mydict[x] = 0
    else:
        continue



def word_finder(keys):
    global mydict

    a = set(['data', 'analytics', 'analyst', 'science', 'python', 'react', 'artificial', 'AI', 'deep', 'machine','learning', 'natural'])
    b = set(['web', 'development', 'android', 'ios', 'java','fullstack'])
    c = set(['UX', 'UI', 'design', 'designer'])
    d = set(['software', 'engineer'])

    for key in keys:
        if len(a.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'data analysis/data science' + ' related course'
            # break
        elif len(b.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'web development' + ' related course'
            # break
        elif len(c.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'UX/UI Design' + ' related course'
            # break
        elif len(d.intersection(set(key.lower().split(" ")))) != 0:
            mydict[key] = 'Back end development' + ' related course'
            # break
        elif key == "No informations":
            mydict[key] = "No Informations"
        else:
            mydict[key] = 'other courses'

    return mydict


word_finder(list(mydict.keys()))

a = comments['program']
comments['courses by group'] = a #create a new column
comments['courses by group'] = comments['courses by group'].replace(mydict)

schools_1 = {
    'ironhack': 10828,
    'app-academy': 10525,
    'le-wagon': 10868,
    'ubiqum-code-academy': 11111,
    'udacity': 11118,
}

comments['school_ID'] = comments['school'].map(schools_1)
comments['concat']=comments['school_ID'].apply(str)+comments['courses by group']
comments=pd.merge(comments,courses['courses_id'], left_on = comments['concat'],right_on = courses['concat'])
list_to_drop=['key_0','anonymous','hostProgramName','isAlumni','tagline','body','review_body','concat']
for x in list_to_drop:
    comments=comments.drop([x], axis=1)

badges_number=['B1','B2','B3','B4','B5','B6','B7']
badges['badges_id'] = badges_number

list_to_drop=['index','concat']
for x in list_to_drop:
    courses=courses.drop([x], axis=1)
    

#Pieter lines

#change index 
#schools = schools.set_index("website")
#badges = badges.set_index("name")
#import the module
#import pymysql
#from sqlalchemy import create_engine

# create sqlalchemy engine
#engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
#                       .format(user="root",
#                              pw="PWWWWW*",
#                              db="ironhack_landscape"))

#Insert whole DataFrame into MySQL
#schools.to_sql('schools', con = engine, if_exists = 'append', chunksize = 1000)
#badges.to_sql('badges', con = engine, if_exists = 'append', chunksize = 1000)
###

/Users/guillaumeaubert/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:64: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

['ironhack', 'app-academy', 'le-wagon', 'ubiqum-code-academy', 'udacity']

In [81]:
badges

,keyword,description,school,school_id,badges_id
name,,,,,
Available Online,available_online,School offers fully online courses,ironhack,10828,B1
Verified Outcomes,verified_outcomes,School publishes a third-party verified outcom...,ironhack,10828,B2
Flexible Classes,flexible_classes,School offers part-time and evening classes,ironhack,10828,B3
Available Online,available_online,School offers fully online courses,app-academy,10525,B4
Job Guarantee,job_guarantee,School guarantees job placement,app-academy,10525,B5
Flexible Classes,flexible_classes,School offers part-time and evening classes,le-wagon,10868,B6
Flexible Classes,flexible_classes,School offers part-time and evening classes,ubiqum-code-academy,11111,B7

In [76]:

comments

,id,name,graduatingYear,jobTitle,createdAt,program,overallScore,overall,curriculum,jobSupport,school,Online/Offline,courses by group,school_ID,courses_id
0,266276,Rebecca Norén,2020,UX-designer,7/9/2020,Web Development Bootcamp,5.0,5.0,5.0,5.0,ironhack,Online/Offline,web development related course,10828,10828_4
1,266276,Rebecca Norén,2020,UX-designer,7/9/2020,Web Development Bootcamp,5.0,5.0,5.0,5.0,ironhack,Online/Offline,web development related course,10828,10828_5
2,266264,William,2020,Front-End Developer,7/9/2020,Web Development Bootcamp,4.7,5.0,5.0,4.0,ironhack,Online/Offline,web development related course,10828,10828_4
3,266264,William,2020,Front-End Developer,7/9/2020,Web Development Bootcamp,4.7,5.0,5.0,4.0,ironhack,Online/Offline,web development related course,10828,10828_5
4,265960,Tim Stephens,2020,full stack web developer/teacher,7/1/2020,Web Development Bootcamp,4.7,5.0,4.0,5.0,ironhack,Online/Offline,web development related course,10828,10828_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13751,259583,Anonymous,2019,None,12/7/2019,Cloud Dev Ops Engineer,5.0,5.0,5.0,5.0,udacity,Offline,Back end development related course,11118,11118_30
13752,259583,Anonymous,2019,None,12/7/2019,Cloud Dev Ops Engineer,5.0,5.0,5.0,5.0,udacity,Offline,Back end development related course,11118,11118_31
13753,264389,Kimi,2020,,5/8/2020,UX Designer,5.0,5.0,5.0,5.0,udacity,Offline,UX/UI Design related course,11118,11118_32
13754,263573,Lia Fazio,2020,None,4/14/2020,UX Designer,4.7,5.0,5.0,4.0,udacity,Offline,UX/UI Design related course,11118,11118_32
13755,258014,Jason M,2017,None,10/23/2019,UX Designer,5.0,5.0,5.0,5.0,udacity,Offline,UX/UI Design related course,11118,11118_32

In [78]:
courses

,courses,school,school_id,courses by group,courses_id
0,Data Analytics Bootcamp,ironhack,10828,data analysis/data science related course,10828_0
1,Data Analytics Part-Time,ironhack,10828,data analysis/data science related course,10828_1
2,UX/UI Design Bootcamp,ironhack,10828,UX/UI Design related course,10828_2
3,UX/UI Design Part-Time,ironhack,10828,UX/UI Design related course,10828_3
4,Web Development Bootcamp,ironhack,10828,web development related course,10828_4
5,Web Development Part-Time,ironhack,10828,web development related course,10828_5
0,Bootcamp Prep,app-academy,10525,other courses,10525_0
1,Software Engineer Track: In-Person,app-academy,10525,Back end development related course,10525_1
2,Software Engineer Track: Online,app-academy,10525,Back end development related course,10525_2
0,Web Development Course - Full-Time,le-wagon,10868,web development related course,10868_0
1,Web Development Course - Part-Time,le-wagon,10868,web development related course,10868_1
2,Data Science - Full-Time,le-wagon,10868,data analysis/data science related course,10868_2
0,Data Analytics & Machine Learning,ubiqum-code-academy,11111,data analysis/data science related course,11111_0
1,Web Development with Java,ubiqum-code-academy,11111,web development related course,11111_1
2,Web Development with JavaScript,ubiqum-code-academy,11111,web development related course,11111_2
0,AI Programming with Python,udacity,11118,data analysis/data science related course,11118_0
1,Al Product Manager,udacity,11118,other courses,11118_1
2,Android Basics,udacity,11118,web development related course,11118_2
3,Android Developer,udacity,11118,web development related course,11118_3
4,Artificial Intelligence,udacity,11118,data analysis/data science related course,11118_4
5,Artificial Intelligence for Trading,udacity,11118,data analysis/data science related course,11118_5
6,Blockchain Developer,udacity,11118,other courses,11118_6
7,Business Analytics,udacity,11118,data analysis/data science related course,11118_7
8,C++,udacity,11118,other courses,11118_8
9,Cloud Dev Ops Engineer,udacity,11118,Back end development related course,11118_9
10,Cloud Developer,udacity,11118,other courses,11118_10
11,Computer Vision,udacity,11118,other courses,11118_11
12,Data Analyst,udacity,11118,data analysis/data science related course,11118_12
13,Data Engineer,udacity,11118,data analysis/data science related course,11118_13
14,Data Structures and Algorithms,udacity,11118,data analysis/data science related course,11118_14
15,Data Visualization,udacity,11118,data analysis/data science related course,11118_15
16,Deep Learning,udacity,11118,data analysis/data science related course,11118_16
17,Deep Reinforcement Learning,udacity,11118,data analysis/data science related course,11118_17
18,Digital Marketing,udacity,11118,other courses,11118_18
19,Front End Web Developer,udacity,11118,web development related course,11118_19
20,Full Stack Web Developer,udacity,11118,web development related course,11118_20
21,Introduction to Machine Learning,udacity,11118,data analysis/data science related course,11118_21
22,Introduction to Programming,udacity,11118,other courses,11118_22
23,iOS Developer,udacity,11118,web development related course,11118_23
24,Java Developer,udacity,11118,web development related course,11118_24
25,Machine Learning Engineer,udacity,11118,data analysis/data science related course,11118_25
26,Marketing Analytics,udacity,11118,data analysis/data science related course,11118_26
27,Natural Language Processing,udacity,11118,data analysis/data science related course,11118_27
28,Predictive Analytics for Business,udacity,11118,data analysis/data science related course,11118_28
29,React,udacity,11118,data analysis/data science related course,11118_29
30,Robotics Software Engineer,udacity,11118,Back end development related course,11118_30
31,Self-Driving Car Engineer,udacity,11118,Back end development related course,11118_31
32,UX Designer,udacity,11118,UX/UI Design related course,11118_32