In [1]:
#create the list of schools we want to study
schools = {
    'ironhack': 10828,
    'app-academy': 10525,
    'le-wagon': 10868,
    'ubiqum-code-academy': 11111,
    'udacity': 11118,
}

import re
import pandas as pd
from pandas.io.json import json_normalize
import requests


def get_comments_school(school):
    #create a regex expressionn that will search for the html tags
    TAG_RE = re.compile(r'<[^>]+>')
    # defines url to make api call to data -> dynamic with school if you want to scrape competition
    url = "https://www.switchup.org/chimera/v1/school-review-list?mainTemplate=school-review-list&path=%2Fbootcamps%2F" + school + "&isDataTarget=false&page=3&perPage=10000&simpleHtml=true&truncationLength=250"
    # makes get request and converts answer to json
    # url defines the page of all the information, request is made, and information is returned to data variable
    data = requests.get(url).json()
    # converts json to dataframe
    reviews = pd.DataFrame(data['content']['reviews'])

    # aux function to apply regex and remove tags
    def remove_tags(x):
        return TAG_RE.sub('', x)
    #create a column in reviews "review_body" that will be populated with another columns created 'body' that will be remove all the html tags
    reviews['review_body'] = reviews['body'].apply(remove_tags)
    # create a column 'school' with the school
    reviews['school'] = school
    #return the table with all the reviews of a defined school
    return reviews



#list comprehension
comments=[get_comments_school(school) for school in schools.keys()]

comments = pd.concat(comments)

from pandas.io.json import json_normalize


def get_school_info(school, school_id):
    #create the URL for each school
    url = 'https://www.switchup.org/chimera/v1/bootcamp-data?mainTemplate=bootcamp-data%2Fdescription&path=%2Fbootcamps%2F' + str(
        school) + '&isDataTarget=false&bootcampId=' + str(
        school_id) + '&logoTag=logo&truncationLength=250&readMoreOmission=...&readMoreText=Read%20More&readLessText=Read%20Less'

    #create a json fil
    data = requests.get(url).json()

    data.keys()

    courses = data['content']['courses']
    courses_df = pd.DataFrame(courses, columns=['courses'])

    locations = data['content']['locations']
    locations_df = json_normalize(locations)

    badges_df = pd.DataFrame(data['content']['meritBadges'])

    website = data['content']['webaddr']
    description = data['content']['description']
    logoUrl = data['content']['logoUrl']
    school_df = pd.DataFrame([website, description, logoUrl]).T
    school_df.columns = ['website', 'description', 'LogoUrl']

    locations_df['school'] = school
    courses_df['school'] = school
    badges_df['school'] = school
    school_df['school'] = school

    # how could you write a similar block of code to the above in order to record the school ID?

    locations_df['school_id'] = school_id
    courses_df['school_id'] = school_id
    badges_df['school_id'] = school_id
    school_df['school_id'] = school_id

    return locations_df, courses_df, badges_df, school_df


locations_list = []
courses_list = []
badges_list = []
schools_list = []

for school, id in schools.items():
    print(school)
    a, b, c, d = get_school_info(school, id)

    locations_list.append(a)
    courses_list.append(b)
    badges_list.append(c)
    schools_list.append(d)

locations = pd.concat(locations_list)
locations.head(10)

courses = pd.concat(courses_list)
courses.head(10)

badges = pd.concat(badges_list)
badges.head(10)

schools = pd.concat(schools_list)
schools



print(schools.head())

ironhack

C:\Users\joanr\anaconda3\lib\site-packages\ipykernel_launcher.py:62: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

app-academy
le-wagon
ubiqum-code-academy
udacity
                                             website  \
0                                www.ironhack.com/en
0                                      appacademy.io
0                                    www.lewagon.com
0  ubiqum.com/?utm_source=switchup&utm_medium=pla...
0  www.udacity.com/?utm_source=switchup&utm_mediu...

                                         description  \
0  <span class="truncatable"><p>Ironhack is a glo...
0  <span class="truncatable"><p>App Academy is a ...
0  <span class="truncatable"><p>Le Wagon runs imm...
0  <span class="truncatable"><p>Ubiqum Code Acade...
0  <span class="truncatable"><p>Udacity is a glob...

                                             LogoUrl               school  \
0  https://d92mrp7hetgfk.cloudfront.net/images/si...             ironhack
0  https://d92mrp7hetgfk.cloudfront.net/images/si...          app-academy
0  https://d92mrp7hetgfk.cloudfront.net/images/si...             le-wagon
0  https://d92mrp7hetgfk.cloudfront.net/images/si...  ubiqum-code-academy
0  https://d92mrp7hetgfk.cloudfront.net/images/si...              udacity

   school_id
0      10828
0      10525
0      10868
0      11111
0      11118

### Null values in every dataframe

In [2]:
courses.isnull().sum()

courses      0
school       0
school_id    0
dtype: int64

In [3]:
schools.isnull().sum()

website        0
description    0
LogoUrl        0
school         0
school_id      0
dtype: int64

In [4]:
locations.isnull().sum()

id                 0
description        0
country.id         3
country.name       3
country.abbrev     3
city.id            3
city.name          3
city.keyword       3
state.id          53
state.name        53
state.abbrev      53
state.keyword     56
school             0
school_id          0
dtype: int64

In [5]:
comments.isnull().sum()

id                    0
name                  0
anonymous             0
hostProgramName    4484
graduatingYear        8
isAlumni             12
jobTitle           3318
tagline               1
body                  0
createdAt             0
queryDate             0
program             632
user                  0
overallScore         11
comments              0
overall              13
curriculum          121
jobSupport          339
review_body           0
school                0
dtype: int64

In [6]:
badges.isnull().sum()

name           0
keyword        0
description    0
school         0
school_id      0
dtype: int64

### Shape of every dataframe

In [7]:
courses.shape

(48, 3)

In [8]:
schools.shape

(5, 5)

In [9]:
locations.shape

(59, 14)

In [10]:
comments.shape

(4768, 20)

In [11]:
badges.shape

(7, 5)

### Dataframe tables

In [12]:
courses

                                courses               school  school_id
0               Data Analytics Bootcamp             ironhack      10828
1              Data Analytics Part-Time             ironhack      10828
2                 UX/UI Design Bootcamp             ironhack      10828
3                UX/UI Design Part-Time             ironhack      10828
4              Web Development Bootcamp             ironhack      10828
5             Web Development Part-Time             ironhack      10828
0                         Bootcamp Prep          app-academy      10525
1    Software Engineer Track: In-Person          app-academy      10525
2       Software Engineer Track: Online          app-academy      10525
0    Web Development Course - Full-Time             le-wagon      10868
1    Web Development Course - Part-Time             le-wagon      10868
2              Data Science - Full-Time             le-wagon      10868
0     Data Analytics & Machine Learning  ubiqum-code-academy      11111
1             Web Development with Java  ubiqum-code-academy      11111
2       Web Development with JavaScript  ubiqum-code-academy      11111
0            AI Programming with Python              udacity      11118
1                    Al Product Manager              udacity      11118
2                        Android Basics              udacity      11118
3                     Android Developer              udacity      11118
4               Artificial Intelligence              udacity      11118
5   Artificial Intelligence for Trading              udacity      11118
6                  Blockchain Developer              udacity      11118
7                    Business Analytics              udacity      11118
8                                   C++              udacity      11118
9                Cloud Dev Ops Engineer              udacity      11118
10                      Cloud Developer              udacity      11118
11                      Computer Vision              udacity      11118
12                         Data Analyst              udacity      11118
13                        Data Engineer              udacity      11118
14       Data Structures and Algorithms              udacity      11118
15                   Data Visualization              udacity      11118
16                        Deep Learning              udacity      11118
17          Deep Reinforcement Learning              udacity      11118
18                    Digital Marketing              udacity      11118
19              Front End Web Developer              udacity      11118
20             Full Stack Web Developer              udacity      11118
21     Introduction to Machine Learning              udacity      11118
22          Introduction to Programming              udacity      11118
23                        iOS Developer              udacity      11118
24                       Java Developer              udacity      11118
25            Machine Learning Engineer              udacity      11118
26                  Marketing Analytics              udacity      11118
27          Natural Language Processing              udacity      11118
28    Predictive Analytics for Business              udacity      11118
29                                React              udacity      11118
30           Robotics Software Engineer              udacity      11118
31            Self-Driving Car Engineer              udacity      11118
32                          UX Designer              udacity      11118

In [13]:
schools

,website,description,LogoUrl,school,school_id
0,www.ironhack.com/en,"<span class=""truncatable""><p>Ironhack is a glo...",https://d92mrp7hetgfk.cloudfront.net/images/si...,ironhack,10828
0,appacademy.io,"<span class=""truncatable""><p>App Academy is a ...",https://d92mrp7hetgfk.cloudfront.net/images/si...,app-academy,10525
0,www.lewagon.com,"<span class=""truncatable""><p>Le Wagon runs imm...",https://d92mrp7hetgfk.cloudfront.net/images/si...,le-wagon,10868
0,ubiqum.com/?utm_source=switchup&utm_medium=pla...,"<span class=""truncatable""><p>Ubiqum Code Acade...",https://d92mrp7hetgfk.cloudfront.net/images/si...,ubiqum-code-academy,11111
0,www.udacity.com/?utm_source=switchup&utm_mediu...,"<span class=""truncatable""><p>Udacity is a glob...",https://d92mrp7hetgfk.cloudfront.net/images/si...,udacity,11118

In [14]:
locations

,id,description,country.id,country.name,country.abbrev,city.id,city.name,city.keyword,state.id,state.name,state.abbrev,state.keyword,school,school_id
0,15901,"Berlin, Germany",57.0,Germany,DE,31156.0,Berlin,berlin,NaN,NaN,NaN,NaN,ironhack,10828
1,16022,"Mexico City, Mexico",29.0,Mexico,MX,31175.0,Mexico City,mexico-city,NaN,NaN,NaN,NaN,ironhack,10828
2,16086,"Amsterdam, Netherlands",59.0,Netherlands,NL,31168.0,Amsterdam,amsterdam,NaN,NaN,NaN,NaN,ironhack,10828
3,16088,"Sao Paulo, Brazil",42.0,Brazil,BR,31121.0,Sao Paulo,sao-paulo,NaN,NaN,NaN,NaN,ironhack,10828
4,16109,"Paris, France",38.0,France,FR,31136.0,Paris,paris,NaN,NaN,NaN,NaN,ironhack,10828
5,16375,"Miami, FL, United States",1.0,United States,US,31.0,Miami,miami,11.0,Florida,FL,florida,ironhack,10828
6,16376,"Madrid, Spain",12.0,Spain,ES,31052.0,Madrid,madrid,NaN,NaN,NaN,NaN,ironhack,10828
7,16377,"Barcelona, Spain",12.0,Spain,ES,31170.0,Barcelona,barcelona,NaN,NaN,NaN,NaN,ironhack,10828
8,16709,"Lisbon, Portugal",28.0,Portugal,PT,31075.0,Lisbon,lisbon,NaN,NaN,NaN,NaN,ironhack,10828
9,17233,Online,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Online,Online,NaN,ironhack,10828
0,15704,"San Francisco, CA, United States",1.0,United States,US,13.0,San Francisco,san-francisco,6.0,California,CA,california,app-academy,10525
1,15705,"New York City, NY, United States",1.0,United States,US,1507.0,New York City,new-york-city,34.0,New York,NY,new-york,app-academy,10525
2,15862,Online,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Online,Online,NaN,app-academy,10525
0,15803,"Melbourne, Australia",20.0,Australia,AU,31174.0,Melbourne,melbourne,NaN,NaN,NaN,NaN,le-wagon,10868
1,15904,"Casablanca, Morocco",44.0,Morocco,MA,31119.0,Casablanca,casablanca,NaN,NaN,NaN,NaN,le-wagon,10868
2,15906,"Buenos Aires, Argentina",60.0,Argentina,AR,31171.0,Buenos Aires,buenos-aires,NaN,NaN,NaN,NaN,le-wagon,10868
3,15964,"Brussels, Belgium",46.0,Belgium,BE,31125.0,Brussels,brussels,NaN,NaN,NaN,NaN,le-wagon,10868
4,15979,"Milan, Italy",39.0,Italy,IT,31107.0,Milan,milan,NaN,NaN,NaN,NaN,le-wagon,10868
5,15996,"Chengdu, China",15.0,China,CN,31126.0,Chengdu,chengdu,NaN,NaN,NaN,NaN,le-wagon,10868
6,16039,"Mexico City, Mexico",29.0,Mexico,MX,31175.0,Mexico City,mexico-city,NaN,NaN,NaN,NaN,le-wagon,10868
7,16049,"Amsterdam, Netherlands",59.0,Netherlands,NL,31168.0,Amsterdam,amsterdam,NaN,NaN,NaN,NaN,le-wagon,10868
8,16106,"Sao Paulo, Brazil",42.0,Brazil,BR,31121.0,Sao Paulo,sao-paulo,NaN,NaN,NaN,NaN,le-wagon,10868
9,16124,"Barcelona, Spain",12.0,Spain,ES,31170.0,Barcelona,barcelona,NaN,NaN,NaN,NaN,le-wagon,10868
10,16145,"Bordeaux, France",38.0,France,FR,31124.0,Bordeaux,bordeaux,NaN,NaN,NaN,NaN,le-wagon,10868
11,16146,"Copenhagen, Denmark",47.0,Denmark,DK,31127.0,Copenhagen,copenhagen,NaN,NaN,NaN,NaN,le-wagon,10868
12,16147,"Lille, France",38.0,France,FR,31128.0,Lille,lille,NaN,NaN,NaN,NaN,le-wagon,10868
13,16148,"Lisbon, Portugal",28.0,Portugal,PT,31075.0,Lisbon,lisbon,NaN,NaN,NaN,NaN,le-wagon,10868
14,16149,"Bali, Indonesia",35.0,Indonesia,ID,31169.0,Bali,bali,NaN,NaN,NaN,NaN,le-wagon,10868
15,16150,"Nantes, France",38.0,France,FR,31130.0,Nantes,nantes,NaN,NaN,NaN,NaN,le-wagon,10868
16,16274,"Rio de Janeiro , Brazil",42.0,Brazil,BR,31131.0,Rio de Janeiro,rio-de-janeiro,NaN,NaN,NaN,NaN,le-wagon,10868
17,16275,"Marseille, France",38.0,France,FR,31129.0,Marseille,marseille,NaN,NaN,NaN,NaN,le-wagon,10868
18,16282,"Montreal, Canada",2.0,Canada,CA,31135.0,Montreal,montreal,NaN,NaN,NaN,NaN,le-wagon,10868
19,16283,"Shanghai, China",15.0,China,CN,31108.0,Shanghai,shanghai,NaN,NaN,NaN,NaN,le-wagon,10868
20,16307,"Belo Horizonte, Brazil",42.0,Brazil,BR,31123.0,Belo Horizonte,belo-horizonte,NaN,NaN,NaN,NaN,le-wagon,10868
21,16407,"Tokyo, Japan",48.0,Japan,JP,31132.0,Tokyo,tokyo,NaN,NaN,NaN,NaN,le-wagon,10868
22,16408,"Lyon, France",38.0,France,FR,31106.0,Lyon,lyon,NaN,NaN,NaN,NaN,le-wagon,10868
23,16478,"Tel Aviv, Israel",5.0,Israel,IL,31079.0,Tel Aviv,tel-aviv,NaN,NaN,NaN,NaN,le-wagon,10868
24,16570,"Kyoto, Japan",48.0,Japan,JP,31134.0,Kyoto,kyoto,NaN,NaN,NaN,NaN,le-wagon,10868
25,16765,"Berlin, Germany",57.0,Germany,DE,31156.0,Berlin,berlin,NaN,NaN,NaN,NaN,le-wagon,10868
26,16767,"Paris, France",38.0,France,FR,31136.0,Paris,paris,NaN,NaN,NaN,NaN,le-wagon,10868
27,16775,"Shenzhen, China",15.0,China,CN,31164.0,Shenzhen,shenzhen,NaN,NaN,NaN,NaN,le-wagon,10868
28,16776,"Lausanne, Switzerland",32.0,Switzerland,CH,31163.0,Lausanne,lausanne,NaN,NaN,NaN,NaN,le-wagon,10868
29,16800,"Madrid, Spain",12.0,Spain,ES,31052.0,Madrid,madrid,NaN,NaN,NaN,NaN,le-wagon,10868
30,16804,"Oslo, Norway",52.0,Norway,NO,31145.0,Oslo,oslo,NaN,NaN,NaN,NaN,le-wagon,10868
31,16805,"Rennes, France",38.0,France,FR,31147.0,Rennes,rennes,NaN,NaN,NaN,NaN,le-wagon,10868
32,16936,"Singapore, Singapore",56.0,Singapore,SG,31154.0,Singapore,singapore,NaN,NaN,NaN,NaN,le-wagon,10868
33,16967,"London, England",61.0,England,GB,31176.0,London,london,NaN,NaN,NaN,NaN,le-wagon,10868
34,16968,"Rome, Italy",39.0,Italy,IT,31180.0,Rome,rome,NaN,NaN,NaN,NaN,le-wagon,10868
35,17128,"Stockholm, Sweden",37.0,Sweden,SE,31109.0,Stockholm,stockholm,NaN,NaN,NaN,NaN,le-wagon,10868
36,17129,"Seoul, Korea",55.0,South Korea,KR,31151.0,Seoul,seol,NaN,NaN,NaN,NaN,le-wagon,10868
37,17157,"Istanbul, Turkey",237.0,Turkey,TR,31193.0,Istanbul,istanbul,NaN,NaN,NaN,NaN,le-wagon,10868
38,17188,"Toronto, Canada",2.0,Canada,CA,31152.0,Toronto,toronto,NaN,NaN,NaN,NaN,le-wagon,10868
39,17314,"Dubai, United Arab Emirates",34.0,United Arab Emirates,AE,31093.0,Dubai,dubai,NaN,NaN,NaN,NaN,le-wagon,10868
0,15913,"Berlin, Germany",57.0,Germany,DE,31156.0,Berlin,berlin,NaN,NaN,NaN,NaN,ubiqum-code-academy,11111
1,16118,"Barcelona, Spain",12.0,Spain,ES,31170.0,Barcelona,barcelona,NaN,NaN,NaN,NaN,ubiqum-code-academy,11111
2,16155,"Amsterdam, Netherlands",59.0,Netherlands,NL,31168.0,Amsterdam,amsterdam,NaN,NaN,NaN,NaN,ubiqum-code-academy,11111
3,16577,"Madrid, Spain",12.0,Spain,ES,31052.0,Madrid,madrid,NaN,NaN,NaN,NaN,ubiqum-code-academy,11111
4,17192,"Lisbon, Portugal",28.0,Portugal,PT,31075.0,Lisbon,lisbon,NaN,NaN,NaN,NaN,ubiqum-code-academy,11111
0,15807,Online,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Online,Online,NaN,udacity,11118

In [15]:
comments[2000:2050]

,id,name,anonymous,hostProgramName,graduatingYear,isAlumni,jobTitle,tagline,body,createdAt,queryDate,program,user,overallScore,comments,overall,curriculum,jobSupport,review_body,school
159,263208,Jahaira Castaneda,False,None,2020.0,False,None,Le Wagon - London,"<span class=""truncatable""><p>My choice to join...",4/2/2020,2020-04-02,FullStack program,{'image': None},4.3,[],5.0,5.0,3.0,My choice to join Le Wagon’s 9-week intensive ...,le-wagon
160,263206,Boyan Levchev,False,None,2020.0,False,None,Very happy Le Wagon graduate,"<span class=""truncatable""><p>I was a bit worri...",4/2/2020,2020-04-02,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,I was a bit worried before starting Le Wagon t...,le-wagon
161,263202,Nicoleta Dudau,False,None,2020.0,False,None,Le Wagon Lausanne - my best ever choise,"<span class=""truncatable""><p>After working a f...",4/2/2020,2020-04-02,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,After working a few years in human resourcing ...,le-wagon
162,263188,Tori,False,None,2019.0,False,None,"Great bootcamp, amazing experience","<span class=""truncatable""><p>Before Le Wagon I...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Before Le Wagon I was an Engineer with no real...,le-wagon
163,263178,Yago Lomondo,False,None,2020.0,False,None,It's not about where you are but where you are...,"<span class=""truncatable""><p>Before starting L...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Before starting Le Wagon I was studying engine...,le-wagon
164,263177,Lucas Diniz Cunha,False,None,2020.0,False,None,"Rio #358, the best batch ever!","<span class=""truncatable""><p>- what you did be...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,- what you did before Le Wagon I was/still am ...,le-wagon
165,263176,Vitor Tavares,False,None,2020.0,False,None,Rio #358 batch really changed my life,"<span class=""truncatable""><p>9 hard-working-fa...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,9 hard-working-fast-paced weeks. I need to say...,le-wagon
166,263169,Joaquín Panelati,False,None,2020.0,False,None,When you look back and can't believe how much ...,"<span class=""truncatable""><p>My experience in ...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,My experience in the bootcamp was excellent. T...,le-wagon
167,263153,Mike Warren,False,None,2020.0,False,None,Excellent Experience,"<span class=""truncatable""><p>Le Wagon Tokyo wa...",4/1/2020,2020-04-01,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Le Wagon Tokyo was such an amazing 9-week expe...,le-wagon
168,263115,Kaori Kohama,False,None,2020.0,False,None,Amazing experience at Le Wagon Amsterdam,"<span class=""truncatable""><p>Before starting b...",3/31/2020,2020-03-31,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,"Before starting bootcamp, I had no experience ...",le-wagon
169,263112,Louis Choo-Choy,False,None,2020.0,False,None,what a good time,"<span class=""truncatable""><p>At the time I cam...",3/31/2020,2020-03-31,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,"At the time I came across Le Wagon, I had just...",le-wagon
170,263111,Lea Medrano,False,None,2020.0,False,None,Incredible experience at Le Wagon !,"<span class=""truncatable""><p>I started Le Wago...",3/31/2020,2020-03-31,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I started Le Wagon with no dev background at a...,le-wagon
171,263105,Arnaud Rottier,False,None,2020.0,False,None,9 ouhlala weeks at Le Wagon Tokyo,"<span class=""truncatable""><p>After working as ...",3/31/2020,2020-03-31,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,After working as sales operations manager at a...,le-wagon
172,263104,Ryanda Diedan,False,None,2020.0,False,None,Re-learn all the fundamentals while actually g...,"<span class=""truncatable""><p>I joined Le Wagon...",3/31/2020,2020-03-31,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I joined Le Wagon Tokyo because I need to lear...,le-wagon
173,263103,Morgan Hoare,False,None,2020.0,False,None,Wonderful Experience,"<span class=""truncatable""><p>From the first da...",3/31/2020,2020-03-31,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,From the first day to the last I enjoyed every...,le-wagon
174,263102,antonio sanchez,False,None,2020.0,False,None,Incredible experience at Le Wagon Tokyo,"<span class=""truncatable""><p>Without knowing a...",3/31/2020,2020-03-31,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Without knowing anything about coding i end up...,le-wagon
175,263098,Minh Bui,False,None,2020.0,False,None,The right direction for entering web industry,"<span class=""truncatable""><p>Let be honest, th...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"Let be honest, this program is hard, freaking ...",le-wagon
176,263081,Iram,False,None,2020.0,False,None,The best experience!,"<span class=""truncatable""><p>I joined Le Wagon...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I joined Le Wagon in 2020. It was a tough 9 we...,le-wagon
177,263079,Jose I. Jerez Torrens,False,None,2020.0,False,None,Amazing boot camp!,"<span class=""truncatable""><p>The most amazing ...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,The most amazing bootcamp. Is really hard a lo...,le-wagon
178,263078,Thomas Van Holder,False,None,2020.0,False,None,A+ Teachers * A+ Curriculum * Cool vibe = Expo...,"<span class=""truncatable""><p>Le Wagon makes le...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Le Wagon makes learning to code accessible to ...,le-wagon
179,263066,Augustin Brun,False,None,2020.0,False,None,My favorite decision,"<span class=""truncatable""><p>What I did before...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,What I did before: I was a student in Business...,le-wagon
180,263064,Nour Souid,False,None,2020.0,False,None,Great Investment,"<span class=""truncatable""><p>I completed Le Wa...",3/30/2020,2020-03-30,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I completed Le Wagon course in March 2020. Bef...,le-wagon
181,263041,John Marsden,False,None,2020.0,False,None,A great 9 weeks,"<span class=""truncatable""><p>Before I attended...",3/28/2020,2020-03-28,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,Before I attended LeWagon I had worked as a mo...,le-wagon
182,263040,Elie Francis,False,None,2020.0,False,None,The Best,"<span class=""truncatable""><p>Before joining Le...",3/28/2020,2020-03-28,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"Before joining Le Wagon, I was in the marketin...",le-wagon
183,263032,Katie King,False,None,2020.0,False,None,Invaluable Learning Experience,"<span class=""truncatable""><p>I've just complet...",3/27/2020,2020-03-27,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I've just completed the nine week Le Wagon web...,le-wagon
184,263020,Dee Lye,False,None,2020.0,False,None,One of the BEST experiences of my life!,"<span class=""truncatable""><p>Wow, what an incr...",3/27/2020,2020-03-27,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"Wow, what an incredibly challenging, rewarding...",le-wagon
185,263015,Evan Byrd,False,None,2020.0,False,None,A great investment of time and energy,"<span class=""truncatable""><p>Formerly a Produc...",3/27/2020,2020-03-27,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,Formerly a Product Manager and consultant in t...,le-wagon
186,263014,Alexander Stewart,False,None,2020.0,False,None,Le Wagon London,"<span class=""truncatable""><p>Prior to enrollin...",3/27/2020,2020-03-27,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,Prior to enrolling in the Le Wagon bootcamp I ...,le-wagon
187,263013,Rory O'Neill,False,None,2020.0,False,None,Learn to code. Change your life...,"<span class=""truncatable""><p>After 10 years ru...",3/27/2020,2020-03-27,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,After 10 years running pubs in and around Lond...,le-wagon
188,263000,Katell GOAER,False,None,2020.0,False,None,Le Wagon Montreal (#367),"<span class=""truncatable""><p>I have completed ...",3/26/2020,2020-03-26,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,I have completed Le Wagon Montreal coding boot...,le-wagon
189,262988,Eva Kramer,False,None,2020.0,False,None,Great experience,"<span class=""truncatable""><p>I worked in vario...",3/26/2020,2020-03-26,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I worked in various commercial roles over the ...,le-wagon
190,262983,Diego Larraz,False,None,2020.0,False,None,Best decision I have made,"<span class=""truncatable""><p>Throughout my und...",3/26/2020,2020-03-26,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Throughout my undergraduate degree in Business...,le-wagon
191,262979,Theo Vergé,False,None,2020.0,False,None,Le Wagon London (#361),"<span class=""truncatable""><p>Before starting l...",3/26/2020,2020-03-26,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,"Before starting le Wagon, I was working in a s...",le-wagon
192,262974,William Price,False,None,2020.0,False,None,Le Wagon Bali (#349),"<span class=""truncatable""><p>Personal Backgrou...",3/26/2020,2020-03-26,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Personal BackgroundI joined Le Wagon because I...,le-wagon
193,262945,Pedro Arthur,False,None,2020.0,False,None,My great experience at Le Wagon (Rio #358),"<span class=""truncatable""><p>As I was finishin...",3/23/2020,2020-03-23,FullStack program,{'image': None},4.7,[],5.0,5.0,4.0,As I was finishing my studies at UFRJ as a Gra...,le-wagon
194,262918,Rose Grondin,False,None,2020.0,False,None,Best choice I ever made,"<span class=""truncatable""><p>I wanted to chang...",3/22/2020,2020-03-22,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I wanted to change my career path and coming f...,le-wagon
195,262871,Stephanie Sassier-Petit,False,None,2020.0,False,None,Best experience with Le Wagon,"<span class=""truncatable""><p>J’ai longtemps ch...",3/20/2020,2020-03-20,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,J’ai longtemps cherché pourquoi j’étais faite....,le-wagon
196,262845,De Malherbe Quentin,False,None,2020.0,False,None,Le Wagon Bordeaux,"<span class=""truncatable""><p>Je viens tout jus...",3/19/2020,2020-03-19,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Je viens tout juste de terminer le bootcamp du...,le-wagon
197,262830,De Malherbe Quentin,False,None,2020.0,False,None,Le Wagon Brodeaux,"<span class=""truncatable""><p></p><p>Je viens t...",3/18/2020,2020-03-18,,{'image': None},5.0,[],5.0,5.0,5.0,Je viens tout juste de terminer le bootcamp du...,le-wagon
198,262822,Mira,False,None,2019.0,False,None,"Le Wagon Chengdu: Great experience, excellent ...","<span class=""truncatable""><p>I researched a nu...",3/18/2020,2020-03-18,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I researched a number of options before choosi...,le-wagon
199,262687,Anonymous,True,None,2019.0,False,None,Le Wagon Montreal Review,"<span class=""truncatable""><p>Le Wagon, what an...",3/11/2020,2020-03-11,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"Le Wagon, what an adventure! I did Le Wagon in...",le-wagon
200,262680,Nicolas DE MIL,False,None,2019.0,False,None,9 weeks to change your life,"<span class=""truncatable""><p>I signed up to Le...",3/11/2020,2020-03-11,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I signed up to Le Wagon after having heard ver...,le-wagon
201,262679,Alan Oliver,False,None,2019.0,False,None,Great and intensive experience teaching solid ...,"<span class=""truncatable""><p>This fullstack pr...",3/11/2020,2020-03-11,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,This fullstack program is a 9 week program whi...,le-wagon
202,262253,Sinan Ucak,False,None,2019.0,False,None,Delivered what was promised !,"<span class=""truncatable""><p>As an engineer, I...",2/26/2020,2020-02-26,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"As an engineer, I already had some programming...",le-wagon
203,262181,Susanna Jacob,False,None,2019.0,False,None,One of my Best Decisions,"<span class=""truncatable""><p>Learning how to c...",2/24/2020,2020-02-24,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Learning how to code had always been a dream -...,le-wagon
204,262151,Felipe de Alba,False,None,2019.0,False,None,I definitely recommend Le Wagon Madrid to anyo...,"<span class=""truncatable""><p>Hello My Name is ...",2/24/2020,2020-02-24,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"Hello My Name is Felipe, and i am a former Stu...",le-wagon
205,262135,Fanny,False,None,2019.0,False,None,"Very impressed, highly recommend!","<span class=""truncatable""><p>I joined the prog...",2/24/2020,2020-02-24,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I joined the program with very high expectatio...,le-wagon
206,262072,Pierre-Emmanuel Tanguy,False,None,2019.0,False,None,Highly Recommend!,"<span class=""truncatable""><p>I initially signe...",2/20/2020,2020-02-20,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,I initially signed up to le wagon to get to kn...,le-wagon
207,262062,Tempels Nathan,False,None,2019.0,False,None,"Great experience, excellent bootcamp","<span class=""truncatable""><p>From cook to deve...",2/20/2020,2020-02-20,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,"From cook to developer in 2 months, it seemed ...",le-wagon
208,262060,Christian Doumit,False,None,2019.0,False,None,Le Wagon : Becoming a new You,"<span class=""truncatable""><p>Story of my life<...",2/20/2020,2020-02-20,FullStack program,{'image': None},5.0,[],5.0,5.0,5.0,Story of my lifeI have always been passionate ...,le-wagon

In [16]:
badges

,name,keyword,description,school,school_id
0,Available Online,available_online,<p>School offers fully online courses</p>,ironhack,10828
1,Verified Outcomes,verified_outcomes,<p>School publishes a third-party verified out...,ironhack,10828
2,Flexible Classes,flexible_classes,<p>School offers part-time and evening classes...,ironhack,10828
0,Available Online,available_online,<p>School offers fully online courses</p>,app-academy,10525
1,Job Guarantee,job_guarantee,<p>School guarantees job placement</p>,app-academy,10525
0,Flexible Classes,flexible_classes,<p>School offers part-time and evening classes...,le-wagon,10868
0,Flexible Classes,flexible_classes,<p>School offers part-time and evening classes...,ubiqum-code-academy,11111

### Data insights

In [44]:
set(courses['courses'].unique())

{'AI Programming with Python',
 'Al Product Manager',
 'Android Basics',
 'Android Developer',
 'Artificial Intelligence',
 'Artificial Intelligence for Trading',
 'Blockchain Developer',
 'Bootcamp Prep',
 'Business Analytics',
 'C++',
 'Cloud Dev Ops Engineer',
 'Cloud Developer',
 'Computer Vision',
 'Data Analyst',
 'Data Analytics & Machine Learning',
 'Data Analytics Bootcamp',
 'Data Analytics Part-Time',
 'Data Engineer',
 'Data Science - Full-Time',
 'Data Structures and Algorithms',
 'Data Visualization',
 'Deep Learning',
 'Deep Reinforcement Learning',
 'Digital Marketing',
 'Front End Web Developer',
 'Full Stack Web Developer',
 'Introduction to Machine Learning',
 'Introduction to Programming',
 'Java Developer',
 'Machine Learning Engineer',
 'Marketing Analytics',
 'Natural Language Processing',
 'Predictive Analytics for Business',
 'React',
 'Robotics Software Engineer',
 'Self-Driving Car Engineer',
 'Software Engineer Track: In-Person',
 'Software Engineer Track: Online',
 'UX Designer',
 'UX/UI Design Bootcamp',
 'UX/UI Design Part-Time',
 'Web Development Bootcamp',
 'Web Development Course - Full-Time',
 'Web Development Course - Part-Time',
 'Web Development Part-Time',
 'Web Development with Java',
 'Web Development with JavaScript',
 'iOS Developer'}

In [46]:
mydict = {}

for x in courses['courses'].unique():
    if x not in mydict.keys():
        mydict[x] = 0
    else:
        continue
mydict

def word_finder(keys):
    global mydict
    
    a = set(['data', 'analytics', 'analyst', 'science'])
    b = set(['web', 'development', 'software', 'developer'])
    c = set(['UX', 'UI', 'design', 'designer'])
    d = set(['online', 'remote'])

    for key in keys:     
        if len(a.intersection(set(key.lower().split(" ")))) != 0 :
            mydict[key] = 'data analysis/data science' + ' related course'
            #break
        elif len(b.intersection(set(key.lower().split(" ")))) != 0 :
            mydict[key] = 'web development' + ' related course'
            #break
        elif len(c.intersection(set(key.lower().split(" ")))) != 0 :
            mydict[key] = 'UX/UI Design' + ' related course'
            #break
        elif len(d.intersection(set(key.lower().split(" ")))) != 0 :
            mydict[key] = 'online course'
            #break
        else:
            mydict[key] = 'other courses'      
            
    return mydict
        
word_finder(list(mydict.keys()))

{'Data Analytics Bootcamp': 'data analysis/data science related course',
 'Data Analytics Part-Time': 'data analysis/data science related course',
 'UX/UI Design Bootcamp': 'UX/UI Design related course',
 'UX/UI Design Part-Time': 'UX/UI Design related course',
 'Web Development Bootcamp': 'web development related course',
 'Web Development Part-Time': 'web development related course',
 'Bootcamp Prep': 'other courses',
 'Software Engineer Track: In-Person': 'web development related course',
 'Software Engineer Track: Online': 'web development related course',
 'Web Development Course - Full-Time': 'web development related course',
 'Web Development Course - Part-Time': 'web development related course',
 'Data Science - Full-Time': 'data analysis/data science related course',
 'Data Analytics & Machine Learning': 'data analysis/data science related course',
 'Web Development with Java': 'web development related course',
 'Web Development with JavaScript': 'web development related course',
 'AI Programming with Python': 'other courses',
 'Al Product Manager': 'other courses',
 'Android Basics': 'other courses',
 'Android Developer': 'web development related course',
 'Artificial Intelligence': 'other courses',
 'Artificial Intelligence for Trading': 'other courses',
 'Blockchain Developer': 'web development related course',
 'Business Analytics': 'data analysis/data science related course',
 'C++': 'other courses',
 'Cloud Dev Ops Engineer': 'other courses',
 'Cloud Developer': 'web development related course',
 'Computer Vision': 'other courses',
 'Data Analyst': 'data analysis/data science related course',
 'Data Engineer': 'data analysis/data science related course',
 'Data Structures and Algorithms': 'data analysis/data science related course',
 'Data Visualization': 'data analysis/data science related course',
 'Deep Learning': 'other courses',
 'Deep Reinforcement Learning': 'other courses',
 'Digital Marketing': 'other courses',
 'Front End Web Developer': 'web development related course',
 'Full Stack Web Developer': 'web development related course',
 'Introduction to Machine Learning': 'other courses',
 'Introduction to Programming': 'other courses',
 'iOS Developer': 'web development related course',
 'Java Developer': 'web development related course',
 'Machine Learning Engineer': 'other courses',
 'Marketing Analytics': 'data analysis/data science related course',
 'Natural Language Processing': 'other courses',
 'Predictive Analytics for Business': 'data analysis/data science related course',
 'React': 'other courses',
 'Robotics Software Engineer': 'web development related course',
 'Self-Driving Car Engineer': 'other courses',
 'UX Designer': 'UX/UI Design related course'}

In [48]:
global mydict
set(mydict.values())

{'UX/UI Design related course',
 'data analysis/data science related course',
 'other courses',
 'web development related course'}

### Creating the new table

In [49]:
courses

,courses,school,school_id,courses by group
0,Data Analytics Bootcamp,ironhack,10828,data analysis/data science related course
1,Data Analytics Part-Time,ironhack,10828,data analysis/data science related course
2,UX/UI Design Bootcamp,ironhack,10828,UX/UI Design related course
3,UX/UI Design Part-Time,ironhack,10828,UX/UI Design related course
4,Web Development Bootcamp,ironhack,10828,web development related course
5,Web Development Part-Time,ironhack,10828,web development related course
0,Bootcamp Prep,app-academy,10525,other courses
1,Software Engineer Track: In-Person,app-academy,10525,other courses
2,Software Engineer Track: Online,app-academy,10525,online course
0,Web Development Course - Full-Time,le-wagon,10868,web development related course
1,Web Development Course - Part-Time,le-wagon,10868,web development related course
2,Data Science - Full-Time,le-wagon,10868,data analysis/data science related course
0,Data Analytics & Machine Learning,ubiqum-code-academy,11111,data analysis/data science related course
1,Web Development with Java,ubiqum-code-academy,11111,web development related course
2,Web Development with JavaScript,ubiqum-code-academy,11111,web development related course
0,AI Programming with Python,udacity,11118,other courses
1,Al Product Manager,udacity,11118,other courses
2,Android Basics,udacity,11118,other courses
3,Android Developer,udacity,11118,other courses
4,Artificial Intelligence,udacity,11118,other courses
5,Artificial Intelligence for Trading,udacity,11118,other courses
6,Blockchain Developer,udacity,11118,other courses
7,Business Analytics,udacity,11118,data analysis/data science related course
8,C++,udacity,11118,other courses
9,Cloud Dev Ops Engineer,udacity,11118,other courses
10,Cloud Developer,udacity,11118,other courses
11,Computer Vision,udacity,11118,other courses
12,Data Analyst,udacity,11118,data analysis/data science related course
13,Data Engineer,udacity,11118,data analysis/data science related course
14,Data Structures and Algorithms,udacity,11118,data analysis/data science related course
15,Data Visualization,udacity,11118,data analysis/data science related course
16,Deep Learning,udacity,11118,other courses
17,Deep Reinforcement Learning,udacity,11118,other courses
18,Digital Marketing,udacity,11118,other courses
19,Front End Web Developer,udacity,11118,web development related course
20,Full Stack Web Developer,udacity,11118,web development related course
21,Introduction to Machine Learning,udacity,11118,other courses
22,Introduction to Programming,udacity,11118,other courses
23,iOS Developer,udacity,11118,other courses
24,Java Developer,udacity,11118,other courses
25,Machine Learning Engineer,udacity,11118,other courses
26,Marketing Analytics,udacity,11118,data analysis/data science related course
27,Natural Language Processing,udacity,11118,other courses
28,Predictive Analytics for Business,udacity,11118,data analysis/data science related course
29,React,udacity,11118,other courses
30,Robotics Software Engineer,udacity,11118,other courses
31,Self-Driving Car Engineer,udacity,11118,other courses
32,UX Designer,udacity,11118,other courses

In [50]:
a = courses['courses']
courses['courses by group'] = a #create a new column

In [51]:
courses

,courses,school,school_id,courses by group
0,Data Analytics Bootcamp,ironhack,10828,Data Analytics Bootcamp
1,Data Analytics Part-Time,ironhack,10828,Data Analytics Part-Time
2,UX/UI Design Bootcamp,ironhack,10828,UX/UI Design Bootcamp
3,UX/UI Design Part-Time,ironhack,10828,UX/UI Design Part-Time
4,Web Development Bootcamp,ironhack,10828,Web Development Bootcamp
5,Web Development Part-Time,ironhack,10828,Web Development Part-Time
0,Bootcamp Prep,app-academy,10525,Bootcamp Prep
1,Software Engineer Track: In-Person,app-academy,10525,Software Engineer Track: In-Person
2,Software Engineer Track: Online,app-academy,10525,Software Engineer Track: Online
0,Web Development Course - Full-Time,le-wagon,10868,Web Development Course - Full-Time
1,Web Development Course - Part-Time,le-wagon,10868,Web Development Course - Part-Time
2,Data Science - Full-Time,le-wagon,10868,Data Science - Full-Time
0,Data Analytics & Machine Learning,ubiqum-code-academy,11111,Data Analytics & Machine Learning
1,Web Development with Java,ubiqum-code-academy,11111,Web Development with Java
2,Web Development with JavaScript,ubiqum-code-academy,11111,Web Development with JavaScript
0,AI Programming with Python,udacity,11118,AI Programming with Python
1,Al Product Manager,udacity,11118,Al Product Manager
2,Android Basics,udacity,11118,Android Basics
3,Android Developer,udacity,11118,Android Developer
4,Artificial Intelligence,udacity,11118,Artificial Intelligence
5,Artificial Intelligence for Trading,udacity,11118,Artificial Intelligence for Trading
6,Blockchain Developer,udacity,11118,Blockchain Developer
7,Business Analytics,udacity,11118,Business Analytics
8,C++,udacity,11118,C++
9,Cloud Dev Ops Engineer,udacity,11118,Cloud Dev Ops Engineer
10,Cloud Developer,udacity,11118,Cloud Developer
11,Computer Vision,udacity,11118,Computer Vision
12,Data Analyst,udacity,11118,Data Analyst
13,Data Engineer,udacity,11118,Data Engineer
14,Data Structures and Algorithms,udacity,11118,Data Structures and Algorithms
15,Data Visualization,udacity,11118,Data Visualization
16,Deep Learning,udacity,11118,Deep Learning
17,Deep Reinforcement Learning,udacity,11118,Deep Reinforcement Learning
18,Digital Marketing,udacity,11118,Digital Marketing
19,Front End Web Developer,udacity,11118,Front End Web Developer
20,Full Stack Web Developer,udacity,11118,Full Stack Web Developer
21,Introduction to Machine Learning,udacity,11118,Introduction to Machine Learning
22,Introduction to Programming,udacity,11118,Introduction to Programming
23,iOS Developer,udacity,11118,iOS Developer
24,Java Developer,udacity,11118,Java Developer
25,Machine Learning Engineer,udacity,11118,Machine Learning Engineer
26,Marketing Analytics,udacity,11118,Marketing Analytics
27,Natural Language Processing,udacity,11118,Natural Language Processing
28,Predictive Analytics for Business,udacity,11118,Predictive Analytics for Business
29,React,udacity,11118,React
30,Robotics Software Engineer,udacity,11118,Robotics Software Engineer
31,Self-Driving Car Engineer,udacity,11118,Self-Driving Car Engineer
32,UX Designer,udacity,11118,UX Designer

In [52]:
mydict

{'Data Analytics Bootcamp': 'data analysis/data science related course',
 'Data Analytics Part-Time': 'data analysis/data science related course',
 'UX/UI Design Bootcamp': 'UX/UI Design related course',
 'UX/UI Design Part-Time': 'UX/UI Design related course',
 'Web Development Bootcamp': 'web development related course',
 'Web Development Part-Time': 'web development related course',
 'Bootcamp Prep': 'other courses',
 'Software Engineer Track: In-Person': 'web development related course',
 'Software Engineer Track: Online': 'web development related course',
 'Web Development Course - Full-Time': 'web development related course',
 'Web Development Course - Part-Time': 'web development related course',
 'Data Science - Full-Time': 'data analysis/data science related course',
 'Data Analytics & Machine Learning': 'data analysis/data science related course',
 'Web Development with Java': 'web development related course',
 'Web Development with JavaScript': 'web development related course',
 'AI Programming with Python': 'other courses',
 'Al Product Manager': 'other courses',
 'Android Basics': 'other courses',
 'Android Developer': 'web development related course',
 'Artificial Intelligence': 'other courses',
 'Artificial Intelligence for Trading': 'other courses',
 'Blockchain Developer': 'web development related course',
 'Business Analytics': 'data analysis/data science related course',
 'C++': 'other courses',
 'Cloud Dev Ops Engineer': 'other courses',
 'Cloud Developer': 'web development related course',
 'Computer Vision': 'other courses',
 'Data Analyst': 'data analysis/data science related course',
 'Data Engineer': 'data analysis/data science related course',
 'Data Structures and Algorithms': 'data analysis/data science related course',
 'Data Visualization': 'data analysis/data science related course',
 'Deep Learning': 'other courses',
 'Deep Reinforcement Learning': 'other courses',
 'Digital Marketing': 'other courses',
 'Front End Web Developer': 'web development related course',
 'Full Stack Web Developer': 'web development related course',
 'Introduction to Machine Learning': 'other courses',
 'Introduction to Programming': 'other courses',
 'iOS Developer': 'web development related course',
 'Java Developer': 'web development related course',
 'Machine Learning Engineer': 'other courses',
 'Marketing Analytics': 'data analysis/data science related course',
 'Natural Language Processing': 'other courses',
 'Predictive Analytics for Business': 'data analysis/data science related course',
 'React': 'other courses',
 'Robotics Software Engineer': 'web development related course',
 'Self-Driving Car Engineer': 'other courses',
 'UX Designer': 'UX/UI Design related course'}

### Final courses table

In [54]:
courses['courses by group'] = courses['courses by group'].replace(mydict)
courses

,courses,school,school_id,courses by group
0,Data Analytics Bootcamp,ironhack,10828,data analysis/data science related course
1,Data Analytics Part-Time,ironhack,10828,data analysis/data science related course
2,UX/UI Design Bootcamp,ironhack,10828,UX/UI Design related course
3,UX/UI Design Part-Time,ironhack,10828,UX/UI Design related course
4,Web Development Bootcamp,ironhack,10828,web development related course
5,Web Development Part-Time,ironhack,10828,web development related course
0,Bootcamp Prep,app-academy,10525,other courses
1,Software Engineer Track: In-Person,app-academy,10525,web development related course
2,Software Engineer Track: Online,app-academy,10525,web development related course
0,Web Development Course - Full-Time,le-wagon,10868,web development related course
1,Web Development Course - Part-Time,le-wagon,10868,web development related course
2,Data Science - Full-Time,le-wagon,10868,data analysis/data science related course
0,Data Analytics & Machine Learning,ubiqum-code-academy,11111,data analysis/data science related course
1,Web Development with Java,ubiqum-code-academy,11111,web development related course
2,Web Development with JavaScript,ubiqum-code-academy,11111,web development related course
0,AI Programming with Python,udacity,11118,other courses
1,Al Product Manager,udacity,11118,other courses
2,Android Basics,udacity,11118,other courses
3,Android Developer,udacity,11118,web development related course
4,Artificial Intelligence,udacity,11118,other courses
5,Artificial Intelligence for Trading,udacity,11118,other courses
6,Blockchain Developer,udacity,11118,web development related course
7,Business Analytics,udacity,11118,data analysis/data science related course
8,C++,udacity,11118,other courses
9,Cloud Dev Ops Engineer,udacity,11118,other courses
10,Cloud Developer,udacity,11118,web development related course
11,Computer Vision,udacity,11118,other courses
12,Data Analyst,udacity,11118,data analysis/data science related course
13,Data Engineer,udacity,11118,data analysis/data science related course
14,Data Structures and Algorithms,udacity,11118,data analysis/data science related course
15,Data Visualization,udacity,11118,data analysis/data science related course
16,Deep Learning,udacity,11118,other courses
17,Deep Reinforcement Learning,udacity,11118,other courses
18,Digital Marketing,udacity,11118,other courses
19,Front End Web Developer,udacity,11118,web development related course
20,Full Stack Web Developer,udacity,11118,web development related course
21,Introduction to Machine Learning,udacity,11118,other courses
22,Introduction to Programming,udacity,11118,other courses
23,iOS Developer,udacity,11118,web development related course
24,Java Developer,udacity,11118,web development related course
25,Machine Learning Engineer,udacity,11118,other courses
26,Marketing Analytics,udacity,11118,data analysis/data science related course
27,Natural Language Processing,udacity,11118,other courses
28,Predictive Analytics for Business,udacity,11118,data analysis/data science related course
29,React,udacity,11118,other courses
30,Robotics Software Engineer,udacity,11118,web development related course
31,Self-Driving Car Engineer,udacity,11118,other courses
32,UX Designer,udacity,11118,UX/UI Design related course